apps/content/urls.py
from django.conf.urls import url

from apps.content.views.categories import CategoryListView, CategoryDetailView
from apps.content.views.contents import ContentDateDetail
from apps.content.views.search import ContentEntrySearch
from apps.content.views.tags import TagListView, TagDetail
from apps.content.views.archive import BlogMonthArchiveView

app_name = 'content'

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        ContentDateDetail.as_view(),
        name='content_entry_detail'),
    url(r'^search/$', ContentEntrySearch.as_view(), name='content_entry_search'),

]

urlpatterns += [
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^categories/(?P<path>[-\/\w]+)/$', CategoryDetailView.as_view(), name='category_detail'),
]

urlpatterns += [
    url(r'^tags/$', TagListView.as_view(), name='tag_list'),
    url(r'^tags/(?P<tag>[^/]+(?u))/$', TagDetail.as_view(), name='tag_detail'),
]

urlpatterns += [
    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/$',
        BlogMonthArchiveView.as_view(),
        name='archive_month'),
]

apps/core/urls.py
from django.conf.urls import url

from apps.content.views.short_link import ContentEntryShortLink
# from apps.slide.views.short_link import GoogleSlideShortLink
from .views import LandingPageView

app_name = 'core'
urlpatterns = [
    url(r'^$', view=LandingPageView.as_view(), name='landing_page'),
    url(r'^(?P<token>[\dA-Z]+)/$',
        ContentEntryShortLink.as_view(),
        name='content_entry_short_link'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^redactor/', include('redactor.urls')),
                  url(r'^', include('apps.core.urls')),
                  url(r'^contents/', include('apps.content.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/base_models/models.py
# Create your models here.

"""Category model for all type """
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from mptt.managers import TreeManager
from mptt.models import MPTTModel
from mptt.models import TreeForeignKey


@python_2_unicode_compatible
class AbstractCategory(MPTTModel):
    """
    Simple model for categorizing entries.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('parent category'))

    objects = TreeManager()

    @property
    def is_parent(self):
        if not self.parent_id:
            return True

    @property
    def tree_path(self):
        """
        Returns category's tree path
        by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    def __str__(self):
        return self.title

    class Meta:
        """
        Category's meta informations.
        """
        abstract = True
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta informations.
        """
        order_insertion_by = ['title']

apps/core/models/category.py
"""Category model for all type """
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from mptt.managers import TreeManager
from mptt.models import MPTTModel
from mptt.models import TreeForeignKey


@python_2_unicode_compatible
class AbstractCategory(MPTTModel):
    """
    Simple model for categorizing entries.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_('parent category'))

    objects = TreeManager()

    @property
    def is_parent(self):
        if not self.parent_id:
            return True

    @property
    def tree_path(self):
        """
        Returns category's tree path
        by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    def __str__(self):
        return self.title

    class Meta:
        """
        Category's meta informations.
        """
        abstract = True
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta informations.
        """
        order_insertion_by = ['title']

apps/content/views/archive.py
from django.views.generic.dates import MonthArchiveView
from apps.content.models.content import ContentEntry

class BlogMonthArchiveView(MonthArchiveView):
    paginate_by = 10
    date_field = 'publication_date'
    template_name = 'content/archive_month.html'
    queryset = ContentEntry.published.all()
    context_object_name = 'contents'

apps/content/views/categories.py
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from apps.content.models.category import Category


def get_category_or_404(path):
    """
    Retrieve a Category Instance
    find slug of the category by splitting the category path
    :param path: path of the category
    :return: return Category
    """
    path_bits = [p for p in path.split('/') if p]
    return get_object_or_404(Category, slug=path_bits[-1])


class CategoryListView(ListView):
    template_name = 'content/category_list.html'

    def get_queryset(self):
        return Category.objects.all().annotate(count_contents_published=Count('entries'))


class BaseCategoryDetail(object):
    def get_queryset(self):
        """

        :return: Contents published of the related categories
        """

        self.category = get_category_or_404(self.kwargs['path'])

        return self.category.contents_published  # return all the queries containing content_entry ie related name entries

    def get_context_data(self, **kwargs):
        """

        :param kwargs:
        :return: current category in context
        """

        context = super().get_context_data(**kwargs)
        context['category'] = self.category

        return context


class CategoryDetailView(BaseCategoryDetail, ListView):
    template_name = 'content/category_content_list.html'
    context_object_name = 'contents'

apps/content/views/tags.py
from django.http import Http404
from django.views.generic import ListView
from tagging.models import Tag, TaggedItem
from tagging.utils import calculate_cloud, get_tag

from apps.content.models import ContentEntry


class TagListView(ListView):
    template_name = 'content/tag_list.html'

    def get_queryset(self):
        tags = Tag.objects.usage_for_queryset(
            ContentEntry.published.all(), counts=True)

        return calculate_cloud(tags, steps=6)


class BaseTagDetail(object):
    def get_queryset(self):
        self.tag = get_tag(self.kwargs['tag'])
        if self.tag is None:
            raise Http404("Matching tags not found".format(self.kwargs
                                                           ['tag']))
        return TaggedItem.objects.get_by_model(ContentEntry.published.all(), self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class TagDetail(BaseTagDetail, ListView):
    template_name = 'content/tag_detail.html'
    context_object_name = 'contents'

apps/core/views.py
from django.views.generic import ListView

# Create your views here.
from apps.content.models import ContentEntry
from apps.core.constants import PUBLISHED


class LandingPageView(ListView):
    model = ContentEntry
    template_name = 'pages/landing_page.html'
    paginate_by = 8
    context_object_name = 'contents'

    def get_queryset(self):
        return super().get_queryset().filter(status=PUBLISHED)

apps/core/templates/appearance/tags/widgets/archive.html
<div class="card-block border-0 pb-2 px-3">
    <div class="card-block p-0 m-0">
        <h6 class="strong card-title text-md-left">
            Archives
        </h6>
    </div>
    <div class="card-block p-0 m-0">
        <ul class="list-unstyled small border-0 m-0 p-0">
            {% for d in dates %}
                <li>
                    <a href="{% url 'content:archive_month' d|date:"o" d|date:"b" %}">{{ d|date:"F o" }}</a>
                </li>
            {% empty %}
                <li>No archives yet.</li>
            {% endfor %}
        </ul>
    </div>
</div>

apps/core/templates/appearance/tags/widgets/categories.html
<div class="card-block border-0 pb-2 px-3">
    <div class="card-block p-0 m-0">
        <a href="{% url 'content:categories' %}">
            <h6 class="strong card-title text-md-left">
                Categories
            </h6>
        </a>
    </div>
    <div class="card-block p-0 m-0">
        <ul class="list-unstyled small border-0 m-0 p-0">
            {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}">
                    {{ category.title|title }} <span
                        class="badge bg-grey-50 green-900 badge-pill">{{ category.count_published_content_entries }}</span></a>
                </li>
            {% empty %}
                <li>No categories yet.</li>
            {% endfor %}
        </ul>
    </div>
</div>

apps/core/templates/appearance/tags/widgets/contents_recent.html
<div class="card-block border-0 pb-2 px-3">
    <div class="card-block p-0 m-0">
        <h6 class="card-title text-md-left">
            Recent Posts
        </h6>
    </div>
    <div class="card-block p-0 m-0">
        <ul class="list-unstyled small border-0 m-0 p-0">
            {% if not contents %}
                <li class="">No contents yet.</li>
            {% else %}
                {% for content in contents %}
                    <li>
                        <a href="{{ content.get_absolute_url }}" class="py-1">
                            {{ content.title|truncatechars:'100' }}
                        </a>
                    </li>
                {% endfor %}
            {% endif %}

        </ul>
    </div>
</div>

apps/core/templates/appearance/tags/widgets/search_bar.html
<div class="border-0 pb-2 px-3">
    <div class="text-md-left pb-2">
        <strong>Search {{ company_name }} blog </strong>
    </div>
    <form class="form-inline small" action="{% url 'content:content_entry_search' %}"
          method="get">
        <div class="input-group">{{ request.GET.q }}
            <input type="text" class="form-control" height="2" name='q' value="{{ q }}" placeholder="Search blog...">
            <span class="input-group-btn">
                      <button class="btn btn-outline-info my-2 my-sm-0" type="submit"><i
                              class="fa fa-search"></i></button>

            </span>
        </div>
    </form>
</div>