apps/content/urls.py
from django.conf.urls import url

from apps.content.views.categories import CategoryListView, CategoryDetailView
from apps.content.views.contents import ContentDateDetail
from apps.content.views.search import ContentEntrySearch
from apps.content.views.tags import TagListView, TagDetail
from apps.content.views.archive import BlogMonthArchiveView

app_name = 'content'

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        ContentDateDetail.as_view(),
        name='content_entry_detail'),
    url(r'^search/$', ContentEntrySearch.as_view(), name='content_entry_search'),

]

urlpatterns += [
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^categories/(?P<path>[-\/\w]+)/$', CategoryDetailView.as_view(), name='category_detail'),
]

urlpatterns += [
    url(r'^tags/$', TagListView.as_view(), name='tag_list'),
    url(r'^tags/(?P<tag>[^/]+(?u))/$', TagDetail.as_view(), name='tag_detail'),
]

urlpatterns += [
    url(r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/$',
        BlogMonthArchiveView.as_view(),
        name='archive_month'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^redactor/', include('redactor.urls')),
                  url(r'^', include('apps.core.urls')),
                  url(r'^contents/', include('apps.content.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/content/models/category.py
from django.urls import reverse

from apps.content.managers import contents_published, ContentEntryRelatedPublishedManager
from apps.core.models.category import AbstractCategory


class Category(AbstractCategory):
    published_content_entries = ContentEntryRelatedPublishedManager()

    @staticmethod
    def get_all_categories():
        return Category.objects.select_related('parent')

    def get_absolute_url(self):
        return reverse('content:category_detail', kwargs={'path': self.tree_path})

    def contents_published(self):
        # self.entries is a queryset of content_entry of the category
        return contents_published(self.entries)

apps/content/models/content.py
from django.db.models.signals import pre_save
from django.utils.text import slugify

from apps.content.models_bases.content import AbstractEntry, PUBLISHED


class ContentEntry(AbstractEntry):
    @staticmethod
    def get_all_entries():
        queryset = ContentEntry.objects.filter(status=PUBLISHED).order_by('-id', '-publication_date').select_related(
            'user').prefetch_related(
            'categories'
        )
        return queryset


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = ContentEntry.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=ContentEntry)

apps/content/views/archive.py
from django.views.generic.dates import MonthArchiveView
from apps.content.models.content import ContentEntry

class BlogMonthArchiveView(MonthArchiveView):
    paginate_by = 10
    date_field = 'publication_date'
    template_name = 'content/archive_month.html'
    queryset = ContentEntry.published.all()
    context_object_name = 'contents'

apps/content/views/categories.py
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic import ListView

from apps.content.models.category import Category


def get_category_or_404(path):
    """
    Retrieve a Category Instance
    find slug of the category by splitting the category path
    :param path: path of the category
    :return: return Category
    """
    path_bits = [p for p in path.split('/') if p]
    return get_object_or_404(Category, slug=path_bits[-1])


class CategoryListView(ListView):
    template_name = 'content/category_list.html'

    def get_queryset(self):
        return Category.objects.all().annotate(count_contents_published=Count('entries'))


class BaseCategoryDetail(object):
    def get_queryset(self):
        """

        :return: Contents published of the related categories
        """

        self.category = get_category_or_404(self.kwargs['path'])

        return self.category.contents_published  # return all the queries containing content_entry ie related name entries

    def get_context_data(self, **kwargs):
        """

        :param kwargs:
        :return: current category in context
        """

        context = super().get_context_data(**kwargs)
        context['category'] = self.category

        return context


class CategoryDetailView(BaseCategoryDetail, ListView):
    template_name = 'content/category_content_list.html'
    context_object_name = 'contents'

apps/content/views/contents.py
from django.views.generic import DetailView

from apps.content.models import ContentEntry


class ContentDateDetail(DetailView):
    model = ContentEntry
    template_name = 'content/content_detail.html'

    def get_queryset(self):
        return super().get_queryset().select_related('user').prefetch_related('categories')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=None)
        if obj:
            obj.visit_count += 1
            obj.save()

        return obj

apps/content/views/search.py
from django.views.generic import ListView

from apps.content.models import ContentEntry


class BaseContentEntrySearch(object):
    q = ''
    error = None

    def get_queryset(self):
        contents = ContentEntry.published.none()

        if self.request.GET:
            self.q = self.request.GET.get('q', '').strip()
            if self.q:
                if not self.q[0:2].isalnum() and not len(self.q) > 2:
                    self.error = "Search Field must be at least 3 character and starts with alpha or alphanumeric"
                else:
                    contents = ContentEntry.published.search(self.q).distinct()
            else:

                contents = ContentEntry.published.all()
        else:
            self.error = "This is no search Query, please check search  parameter in url"

        return contents

    def get_context_data(self, **kwargs):
        """
        Add Extra data to context ie error and pattern
        :param kwargs: query parameter
        :return: context object
        """
        context = super().get_context_data(**kwargs)
        context.update({
            'error': self.error, 'q': self.q, 'total_query': self.get_queryset().count()
        })
        return context


class ContentEntrySearch(BaseContentEntrySearch, ListView):
    template_name = 'content/content_search.html'
    paginate_by = 1
    context_object_name = 'contents'

    def get_context_data(self, **kwargs):
        return super().get_context_data()

    def get_queryset(self):
        return super().get_queryset().prefetch_related('categories').select_related('user')

apps/content/views/short_link.py
from django.shortcuts import get_object_or_404
from django.views.generic import RedirectView

from apps.content.models import ContentEntry


class ContentEntryShortLink(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        content_entry = get_object_or_404(ContentEntry.published, pk=int(kwargs['token'], 36))
        return content_entry.get_absolute_url()

apps/content/views/tags.py
from django.http import Http404
from django.views.generic import ListView
from tagging.models import Tag, TaggedItem
from tagging.utils import calculate_cloud, get_tag

from apps.content.models import ContentEntry


class TagListView(ListView):
    template_name = 'content/tag_list.html'

    def get_queryset(self):
        tags = Tag.objects.usage_for_queryset(
            ContentEntry.published.all(), counts=True)

        return calculate_cloud(tags, steps=6)


class BaseTagDetail(object):
    def get_queryset(self):
        self.tag = get_tag(self.kwargs['tag'])
        if self.tag is None:
            raise Http404("Matching tags not found".format(self.kwargs
                                                           ['tag']))
        return TaggedItem.objects.get_by_model(ContentEntry.published.all(), self.tag)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class TagDetail(BaseTagDetail, ListView):
    template_name = 'content/tag_detail.html'
    context_object_name = 'contents'

apps/content/templates/content/archive_month.html
{% extends "_base.html" %}

{% load staticfiles thumbnail content static paginator core %}
{% load social_share %}
{% block meta-keywords %}{% if object.tags %}{{ object.tags }}{% else %}{{ block.super }}
{% endif %}{% endblock meta-keywords %}
{% block meta-author %}{{ object.authors.all|join:', ' }},{{ block.super }}{% endblock %}
{% block meta-description %}{% if object.excerpt %}{{ object.excerpt }}{% else %}{{ object.lead }}
{% endif %}{% endblock meta-description %}
{% block og-description %}{% if object.short_description %}{{ object.short_description }}{% else %}{{ object.lead }}
{% endif %}{% endblock og-description %}
{% block og-title %}{% if object.short_title %}{{ object.short_title }}{% else %}{{ object.title }}
{% endif %}{% endblock og-title %}
{% block og-type %}article{% endblock og-type %}
{% block og-url %}{{ HTTP_HOST_NAME_WITH_PROTOCOL }}{{ object.get_absolute_url }}{% endblock og-url %}
{% block link-canonical %}{{ HTTP_HOST_NAME_WITH_PROTOCOL }}{{ object.get_absolute_url }}{% endblock link-canonical %}
{% block og-image %}{% if object.image %}{{ object.image.url }}{% else %}{{ block.super }}
{% endif %}{% endblock og-image %}
{% block title %}Archives - {{ month|date:"F" }}{% endblock %}

{% block content %}
    <h3 class="my-2 pb-2 text-left font-weight-bold">{{ month|date:"F Y" }}</h3>
    {% include 'content/partials/_content_list.html' %}
    {% ajax_paginator %}
{% endblock content %}

apps/content/templates/content/category_content_list.html
{% extends '_base.html' %}
{% block content %}
    <h3 class="my-2 pb-2 text-left font-weight-bold">{{ category }}</h3>
    {% include 'content/partials/_content_list.html' %}
{% endblock %}

apps/content/templates/content/category_list.html
{% extends '_base.html' %}
{% load staticfiles %}
{% load mptt_tags %}
{% load core %}

{% block content %}
    <h3 class="my-2 pb-2 text-left font-weight-bold">Categories</h3>
    <section id="child-category">
        <ul class="root">
            {% recursetree object_list %}
                <li class="parent">
                    <a href="{{ node.get_absolute_url }}"> {{ node.title }} <span
                            class="badge bg-grey-50 text-gray-dark">{{ node.count_contents_published }}</span> </a>
                    {% if not node.is_leaf_node %}
                        <ul class="children">
                            {{ children }}
                        </ul>
                    {% endif %}
                </li>
            {% endrecursetree %}
        </ul>
    </section>
{% endblock %}

apps/content/templates/content/content_detail.html
{% extends '_base.html' %}
{% load staticfiles thumbnail content static  core %}
{% load social_share %}
{% block meta-keywords %}{% if object.tags %}{{ object.tags }}{% else %}{{ block.super }}
{% endif %}{% endblock meta-keywords %}
{% block meta-author %}{{ object.authors.all|join:', ' }},{{ block.super }}{% endblock %}
{% block meta-description %}{% if object.excerpt %}{{ object.excerpt }}{% else %}{{ object.lead }}
{% endif %}{% endblock meta-description %}
{% block og-description %}{% if object.short_description %}{{ object.short_description }}{% else %}{{ object.lead }}
{% endif %}{% endblock og-description %}
{% block og-title %}{% if object.short_title %}{{ object.short_title }}{% else %}{{ object.title }}
{% endif %}{% endblock og-title %}
{% block og-type %}article{% endblock og-type %}
{% block og-url %}{{ HTTP_HOST_NAME_WITH_PROTOCOL }}{{ object.get_absolute_url }}{% endblock og-url %}
{% block link-canonical %}{{ HTTP_HOST_NAME_WITH_PROTOCOL }}{{ object.get_absolute_url }}{% endblock link-canonical %}
{% block og-image %}{% if object.image %}{{ object.image.url }}{% else %}{{ block.super }}
{% endif %}{% endblock og-image %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}

    <div class="card pb-5 m-0 border-0">
        <div class="card-block p-0 m-0 border-0">
            <small class="text-muted">
                {{ object.publication_date|date }}
            </small>
        </div>
        <div class="card-block py-3">
            <a href="{{ object.get_absolute_url }}">
                <h2 class="card-title">{{ object.title }}</h2>
            </a>
            {% if object.image %}
                <p>
                    <img class="figure-img img-fluid w-100 height-400 p-0"
                         src="{{ object.image|thumbnail_url:'thumb-820-400' }}"
                         alt="{{ object.image_caption }}">

                    {% if object.image_source %}
                        <small class="text-muted">Image By: {{ object.image_source }}</small>
                    {% endif %}
                </p>
            {% endif %}

        </div>
        <div class="card-block pb-0">
            {{ object.content|safe }}
        </div>
        <div class="px-3 m-0">
            <hr>
        </div>
        <div class="card-block py-0">
            <p class="text-muted small py-0 m-0">
                <i class="fa fa-user"> </i> Posted By: {{ object.user }}&nbsp;
                <i class="fa fa-calendar"></i>
                <time datetime="{{ object.publication_date|date:'Y-m-d H:i:s' }}"
                      data-toggle="tooltip" data-placement="top"
                      title="{{ object.publication_date|date:'D d M Y H:i:s' }}">
                    at {{ object.publication_date|time }}
                </time>
                in
                {% get_categories_badges_display object.all_categories %}
                <i class="fa fa-eye small"></i> Views: {{ object.visit_count }}&nbsp;
                <i class="fa fa-book"></i> {{ object.read_time }} min read

            </p>
            {% if object.tags_list %}
                <p class="text-muted small py-0 m-0">
                    <i class="fa fa-tags"></i> Tags: {% get_tags_badges_display object.tags_list %}
                </p>
            {% endif %}

        </div>
        <div class="card-block">
            <div class="row small pl-2">
                {% tweet_to_twitter content.title content.short_url %} &nbsp;
                {% share_to_facebook content.title content.short_url %} &nbsp;
                {% share_to_google_plus content.short_url %}
            </div>
        </div>
    </div>
    <script>
        /**
         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

        /*
         var disqus_config = function () {
         this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
         this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
         };
         */
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://healthmandu.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>
{% endblock %}

apps/content/templates/content/content_search.html
{% extends '_base.html' %}
{% load staticfiles thumbnail content static %}
{% load core %}
{% load paginator %}

{% block content %}
    <div class="row">
        <div class="col-md-12 pt-4">
            {% if not contents %}
                {% if error %}
                    <h6 class="alert alert-danger">
                        {{ error }}
                    </h6>
                {% endif %}
                <p class="alert alert-warning">Results not found!! Your search <strong>{{ q }} </strong>did not match
                    any documents</p>
                <h6>Suggestions:</h6>

                <ul>
                    <li>Simplify your search: try fewer or more general keywords</li>
                    <li> Make sure all words are spelled correctly</li>

                    <li>
                        Use keywords that reflect words or phrases likely to be in the text of the item you are
                        seeking
                    </li>
                </ul>

            {% else %}
                {% if page_obj.paginator.count >= 1 %}
                    <h6 class="alert bg-blue-50">
                        Showing {{ page_obj.start_index }} - {{ page_obj.end_index }}
                        of {{ page_obj.paginator.count }}
                        for <strong>{{ q }}</strong>
                    </h6>
                {% else %}
                    No results.
                    <span id="job-count">

                {% endif %}
            </span>
            {% endif %}
            <div class="content-list">
                {% include 'content/partials/_content_list.html' %}
            </div>
            {#            {% pagination is_paginated page_obj paginator %}#}
            <div class="row pb-5">
                <div class="col-md-3">
                </div>
                <div class="col-md-6">

                    {% ajax_paginator %}
                </div>
                <div class="col-md-3">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/content/templates/content/search.html
<div class="col-md-4 p-0">
    <form class="form-inline my-2 my-lg-0 float-right" action="{% url 'content:content_entry_search' %}"
          method="get">
        <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>

apps/content/templates/content/tag_detail.html
{% extends '_base.html' %}
{% block content %}
    <h3 class="my-2 pb-2 text-left font-weight-bold">{{ tag }}</h3>
    {% include 'content/partials/_content_list.html' %}

    {% include 'partials/_paginator.html' %}
{% endblock %}

apps/content/templates/content/tag_list.html
{% extends '_base.html' %}

{% block content %}
    {% load i18n %}
    <div class="card">
        <div class="card-block p-1">
            {% for tag in object_list|dictsortreversed:"count" %}
                <span><a href="{% url 'content:tag_detail' tag.name %}" class="tag-cloud-font-{{ tag.font_size }}">{{ tag }}</a></span>
            {% endfor %}
        </div>
    </div>
{% endblock %}